### PR TITLE
2D Graphics , Line Rendering , SkyBoxes , and editing Mesh to be more "overridable"

### PR DESCRIPTION
**Pull request by fhntv24**
Object2D render: For rendering 2D stuff - like GUIs. Its not affected by light - beacos GUI need to be not effected by light. Fully working this time!
MeshLine: Rendering lines , and not planes.Need to edit Mesh beacos of that...
Mesh: Dont make all varibles private , some need to be protected!
SkyBox: read "SkyBox box , like in real games" for more info

What i'm working on(maybe someone need that?!):
PostLoader: loading stuff in Run-Time. Stuff like world textures , or game models that you dont need to load at game start! Lets load them when game is running! (btw , even multithreaded!)...Fastest loading time!

BitMaps: lets rotate , flip , and do cool stuff with them. maybe lets make even some filters on them! And converting them to textures... And "QualityBitMap" - sizeable BitMap =)

HeightMapMesh: lets load HeightMap from texture to mesh...Uses QualityBitMap , and all other cool BitMap features.Also suports PostLoading.

PostLoadingMesh: Mesh , that does all hes work in "PostLoad" state.Same as other PostLoad features!

Multi-pass rendering: you can use multi-pass rendering for alpha channels...And it works! Alpha channel! http://snag.gy/aX2BG.jpg YAY!
and other cool stuff. And how benny said , will be making seperate fork & project on github.

### CODE REVIEW

**Comment by BennyQBD** [comment]
Hey, it's great to see you're fiddling with the engine and doing your own thing, but this repository is mostly for reference for anyone following along with the tutorials.
Rather than making pull requests, I think it'd be better if you forked the repository and made all the changes in your own copy of the repository. That way, you have all the new tools and features in your repository, and this repository stays useful for reference.

**Comment by fhntv24** [comment]
Maybe then you make other repository? That people can make stuff , to make engine be "real engine"? And really , some of them are bug-fixes , not new features.Like with lightning - its need to be null , beacos we not clearing it from last rendering cycle , and that is "unlogical" , that we having light in ambient - render - pass =) .And that is simple stuff , not super mega advanced stuff, just some usefull stuff , that you can use.I dont think what someone dont know how to render lines , or making 2D rendering happen. Its just some usefull stuff , that maybe even you will need. 

You making awesome stuff like MipMapping , shadows , like Physic engine , or other stuff. Oh , and you making them in C++ - so you can show how to made that stuff if you want to , but in C++ version. And really , that is very low stuff , that noone needs...

p.s. and i dont see shadows in Java engines version.

p.s.s.: Heh , if you dont want to accept this PullRequest , then when you will add RGBA support , or 2D rendering support? Or when you will add sprite support? Or HeightMap loading? Or when you will do animation? 

oh , and do you know some good HeightMap optimizations? So quality can be not that good , but at least  it will not lag on slow machines

**Comment by BennyQBD** [comment]
I mostly agree, but I still think you should make the other repository instead of me. An enhanced version of the 3D engine wouldn't really be my project, and I don't want to accidentally get credit for all the new features everyone else added.

To answer your other questions:
-The Java version doesn't have shadows because I'm doing the new rendering series in the C++ version. I simply don't have the time to maintain two copies of essentially the same code, except in different programming languages. I'm still doing everything I can to make it easy to follow along with the new series in Java if people want to do so, however.

-The engine is already storing textures in RGBA format. If you're talking about transparency, that'll be covered in the rendering series.

-The engine already supports rendering things in 2D: You'll want to make a camera with an identity matrix for the projection, and you'll want to render your 2D objects with square meshes. In this configuration, -1 means the left/bottom of the screen, and 1 means top/right. This means any 2D graphics will be resolution independent, and it also allows reusing the existing transform and rendering tools for 2D.

-Sprites will be automatically supported when transparency support is added. Again, transparency is going to be covered in  the rendering series.

-A HeightMap is simply a greyscale 2D image that represents height information. The engine can already load such a texture. Based on the way you've used the term however, you seem to be talking about a specific usage of HeightMaps, and that I can't answer without knowing what usage you're referring to. Are you talking about using HeightMaps for terrain, perhaps?

-Animation can mean a lot of things. Any animation where objects move/rotate/scale is already supported by the transform system. I'll be covering skeletal animation for characters and such in the rendering series. 2D animation can be performed simply by changing which texture you use for the mesh, as demonstrated in the Wolfenstein 3D clone series. That should cover just about every type of animation you'd want, but if you have something else in mind, let me know!

Finally, for HeightMap optimizations, I'll be more than happy to talk about it once I know what you're trying to use them for. For now, the only thing I can recommend is taking your current heightmap system and actually trying to run it on a slow computer. You might be surprised at how well it performs, and perhaps you'll find that your heightmap system is barely causing a performance issue at all, and it's actually something totally different is causing lag instead. It's always a good idea to find what part of your engine can benefit the most from optimizing, and optimize there first; that way you get better results with less effort.

**Comment by fhntv24** [comment]
- heightmapRENDERER <- i think , i mean rendering them...for terain and stuff.Its alredy made , and works. Why it lags? Lets think why 3D rendering , or actyallu all rendering is slow - memory...memory...transfer rate. Its slowest of all parts , if i'm not mistaking. I'm alredy using VBO , but its not enought for maps 300*300 with lightning. I think "Sizeable BitMap" is ok to fix that problem.
- yea , i'm about Transperency , not RGBA. For good and fast rendering , its better to make multiple pass rendering. How i did it? When first pass is rendering , you call RenderingEngine.addRenderingPass(this) , and it will add you object for next rendering pass. It will infinite loop , so you want to do that when you want. You can get what rendering pass it is , and other sutff like that. I cant explain that , so i think you will do better =)
- Animation , i mean skeletal animation. I'm waiting on that =) I think its biggest part of 3D graphics. And btw , you will need some editor to make it easy , or...it will be hard. What path you will select , hard or easy?)
- 2D render actyallu a liitle bit bigger problem ( how i did find ). What i did - just added my GUI object to cameras object. It works fine for me. Its not greatest solution , but it works. I didnt actyallu update my GitHub project , so you dont see what i did make in the end with 2D mesh. 
- Project at all: heh , if you dont want to make it...Heh , then dont. I dont care if you will take any credits on engine at all...I dont care about it.
- Shadows: yea , that is why i want to make pull requests , beacos of that. 

Some more stuff , not from original answers: Heh , then i will make my fork. All credits i will give to you , or most of them. You did tons of stuff for engine , you is real creator. All what i will do - i will make game , and will make stuff that i didnt have , and upload it to GitHub so someone else can use it. It will be bigger that you wolfens game , but it will be not that big game =). oh , btw i didnt use GitHub at all , that is first time when i'm using it , so i dont know how to make projects here , and Auto-update them with eclipse.Going to find how i can do that , and make "project". Oh , and benny , close this pull request if you dont want to speak with me , and if you dont care about that changes.

**Pull request closed without merging**
